# Generated by Django 4.0 on 2021-12-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now=True)),
                ('promotion_title', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='carousel')),
                ('promotion_url', models.URLField()),
            ],
        ),
    ]
